apiVersion: v1
kind: Service
metadata:
  name: igeraweb
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: igeraweb-http
  selector:
    app: igeraweb