apiVersion: v1
kind: Service
metadata:
  name: igeraweb
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: igeraweb-http
      nodePort: 30001
  selector:
    app: igeraweb